name: hulectures
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

# Versioning for the application
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies required for the project
dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8

  # WebView support
  webview_flutter: ^4.4.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting package
  flutter_lints: ^5.0.0

  # Add launcher icons support
  flutter_launcher_icons: ^0.13.1

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Add assets folder for images (logo)
  assets:
    - assets/android-chrome-512x512-99.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/android-chrome-512x512-99.png" # Use this file as app icon
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/android-chrome-512x512-99.png"
