name: hulectures
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

# Versioning for the application
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies required for the project
dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8

  # WebView support
  webview_flutter: ^4.4.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting package
  flutter_lints: ^5.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true
