// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHZ7lvDhtyk1R2wh8vTVQdink7b8ut2x8',
    appId: '1:711414465595:web:39858efcf8ae7fa83a081e',
    messagingSenderId: '711414465595',
    projectId: 'hu-app-13c68',
    authDomain: 'hu-app-13c68.firebaseapp.com',
    storageBucket: 'hu-app-13c68.firebasestorage.app',
    measurementId: 'G-S45FNFEDW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgHXldL5x34MX34WSU1qORoxL1C2aCtdY',
    appId: '1:711414465595:android:aa40ccab9dff7f303a081e',
    messagingSenderId: '711414465595',
    projectId: 'hu-app-13c68',
    storageBucket: 'hu-app-13c68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHOLteVAvzKW6woDn9cYPndSY13-j7tUg',
    appId: '1:711414465595:ios:0d6286e777c2f9823a081e',
    messagingSenderId: '711414465595',
    projectId: 'hu-app-13c68',
    storageBucket: 'hu-app-13c68.firebasestorage.app',
    iosBundleId: 'com.example.hulectures',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHOLteVAvzKW6woDn9cYPndSY13-j7tUg',
    appId: '1:711414465595:ios:0d6286e777c2f9823a081e',
    messagingSenderId: '711414465595',
    projectId: 'hu-app-13c68',
    storageBucket: 'hu-app-13c68.firebasestorage.app',
    iosBundleId: 'com.example.hulectures',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHZ7lvDhtyk1R2wh8vTVQdink7b8ut2x8',
    appId: '1:711414465595:web:449e85901cec46d53a081e',
    messagingSenderId: '711414465595',
    projectId: 'hu-app-13c68',
    authDomain: 'hu-app-13c68.firebaseapp.com',
    storageBucket: 'hu-app-13c68.firebasestorage.app',
    measurementId: 'G-ZHFTC0PLNC',
  );
}
